config/routes.rb
Rails.application.routes.draw do
  mount Commontator::Engine => '/commontator'

  devise_for :users

  resources :users, only: [:index, :show, :update]
  resources :reflections, only: [:index, :show, :edit, :update]
  resources :reviews, only: [:index, :show, :edit, :update]

  root 'home#index'
  get 'demo', to: 'home#demo'
  get 'about', to: 'home#about'
  get 'users/typeahead/:query', to: 'users#typeahead'
  get 'add_reflection', to: 'reflections#add', as: 'add_reflection'
  get 'reflections/:id/privacy', to: 'reflections#privacy', as: 'reflection_privacy'
  get 'reflections/:id/review', to: 'reflections#review', as: 'reflection_review'
  get 'reflections/:id/settings', to: 'reflections#settings', as: 'reflection_settings'

  post 'reflections/new', to: 'reflections#new', as: 'new_reflection'
  post 'reflections/:id/authorise', to: 'reflections#authorise', as: 'authorise_personals'
  post 'reflections/:id/update_privacy', to: 'reflections#update_privacy', as: 'update_reflection_privacy'
  post 'reflections/:id/', to: 'reflections#submit_for_review', as: 'submit_for_review'
end

app/models/reflection.rb
class Reflection < ApplicationRecord
  enum privacy: [ 'Private', 'Public' ]
  acts_as_commontable

  belongs_to :user

  has_many :reflection_privacies, class_name: "Privacy", foreign_key: "reflection_id"
  has_many :authorised_personals, through: :reflection_privacies, source: :authorised_personal

  has_many :reflection_reviews, class_name: "Review", foreign_key: "reflection_id"
  has_many :reviewers, through: :reflection_reviews, source: :reviewer
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @reflections = Reflection.where(privacy: 1)
    if user_signed_in?
      # @reflections += current_user.request_reflections
      @reflections += current_user.reflections
      @reflections += current_user.visible_reflections
      review_reflections = Reflection.includes(:reflection_reviews)
        .joins(:reflection_reviews)
        .where('reviews.reviewer_id = ?', current_user.id)
      @reflections += review_reflections
      @review_reflection_ids = review_reflections.map {|r| r.id}
    end
    @reflections = @reflections.uniq
    @reflections = @reflections.sort_by &:updated_at
  end

  def add
    @new_reflection = Reflection.new
  end

  def new
    reflection = Reflection.create(
      title: reflection_params[:title],
      story: reflection_params[:story],
      user: current_user)
    flash[:notice] = 'Reflection successfully created!'
    redirect_to reflection_settings_path(reflection)
  end

  def show
    @reflection = Reflection.find(reflection_id_params)
    @reflection_reviews = Review.where(reflection_id: @reflection.id, status: 1)
    commontator_thread_show(@reflection)
  end

  def edit
    @reflection = Reflection.find(reflection_id_params)
  end

  def update
    r = Reflection.find(reflection_id_params)
    if r.user == current_user
      r.title = reflection_params['title']
      r.story = reflection_params['story']
      r.save
      flash[:notice] = 'Reflection successfully updated!'
    else
      flash[:notice] = 'You do not have the rights to edit this reflection!'
    end
    redirect_to reflection_path(r)
  end

  def privacy
    @reflection = Reflection.find(reflection_id_params)
    @personals_json = @reflection.authorised_personals.map { |personal| {'value': "#{personal.name}; #{personal.email}", 'id': "#{personal.id}"} }.to_json
  end

  def review
    @reflection = Reflection.find(reflection_id_params)
    @reviewers_json = @reflection.reviewers.map { |reviewer| {'value': "#{reviewer.name}; #{reviewer.email}", 'id': "#{reviewer.id}"} }.to_json
  end

  def settings
    @reflection = Reflection.find(reflection_id_params)
    @personals_json = @reflection.authorised_personals.map { |personal| {'value': "#{personal.name}; #{personal.email}", 'id': "#{personal.id}"} }.to_json
    @reviewers_json = @reflection.reviewers.map { |reviewer| {'value': "#{reviewer.name}; #{reviewer.email}", 'id': "#{reviewer.id}"} }.to_json
  end

  def authorise
    r = Reflection.find(reflection_id_params)
    authorised_personals = JSON.parse authorised_personals_params
    Privacy.where(reflection: r).delete_all
    if authorised_personals.empty?
      flash[:notice] = 'No users added for sharing!'
      redirect_to :back
      return
    end
    authorised_personals.each do |personal|
      if r.user != personal['id'].to_i
        Privacy.create(reflection_id: reflection_id_params , authorised_personal_id: personal['id'].to_i)
      end
    end
    flash[:notice] = 'Successfully shared reflections!'
    redirect_to :back
  end

  def submit_for_review
    r = Reflection.find(reflection_id_params)
    reviewers = JSON.parse reviewers_params
    reviewers_ids = reviewers.map { |personal| personal['id'].to_i }
    reviewers_remove = r.reviewers.reject { |reviewer| reviewers_ids.include?(reviewer.id) }
    reviewers_remove.each{ |personal| Review.where(reflection: r, reviewer: personal).delete_all } unless reviewers_remove.empty?
    if reviewers.empty?
      flash[:notice] = 'You have not submitted any reviewers!'
      redirect_to :back
      return
    end
    current_reviewers_ids = r.reviewers.map { |personal| personal.id }
    reviewers_create = reviewers.reject{ |personal| current_reviewers_ids.include?(personal['id'].to_i) }
    reviewers_create.each do |personal|
      if r.user != personal['id'].to_i
        Review.create(reflection_id: reflection_id_params , reviewer_id: personal['id'].to_i)
      end
    end
    flash[:notice] = 'Your reflections have been sent for review!'
    redirect_to :back
  end

  def update_privacy
    r = Reflection.find(reflection_id_params)
    if r.user == current_user
      r.privacy = reflection_privacy_params
      r.save
      flash[:notice] = 'Privacy settings successfully udated!'
    else
      flash[:notice] = 'You do not have the rights to edit the privacy setting for this reflection.'
    end
    redirect_to :back
  end

  private
  def reflection_id_params
    params.require(:id)
  end

  def reflection_params
    params.require(:reflection).permit(
      :title,
      :story)
  end

  def reflection_privacy_params
    params.require(:privacy)
  end

  def authorised_personals_params
    params.require(:authorised_personals)
  end

  def reviewers_params
    params.require(:reviewers)
  end
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
  def reflection_card_class(reflection, review)
    if user_signed_in?
      if !review.nil?
        class_string = 'warning'
      elsif reflection.user == current_user
        class_string = 'primary'
      else
        class_string = 'info'
      end
    else
      class_string = 'info'
    end
    return class_string
  end

  def reflection_card_description(reflection)
    if reflection.user == current_user
      description_string = 'Personal reflection'
    elsif reflection.privacy == 'Private'
      description_string = 'Shared with you'
    else
      description_string = 'Public reflection'
    end
    return description_string
  end

  def privacy_share_form(privacy)
    if privacy == 'Private'
      return {tag: 'div', class: 'form-group'}
    else
      return {tag: 'div', class: 'form-group', hidden: ''}
    end
  end
end

app/views/reflections/add.html.slim
.container
  h3.mt-2 New Reflection
  = simple_form_for @new_reflection, url: new_reflection_path do |f|
    .row.form-group
      .col-md-12
        = f.input_field :title, placeholder: 'Reflection Title', class: 'form-control', id: 'reflectionTitle'
    .row.form-group
      .col-md-12
        = f.text_area :story, placeholder: 'Write your story here', class: 'form-control summernote', id: 'reflectionStory', rows: 20
    .row.form-group
      .col-md-12
        = f.button :submit, 'Create', class: 'btn btn-primary mr-1'
        = link_to 'back', user_path(current_user), class: 'btn btn-light'

app/views/reflections/edit.html.slim
.container
  h3.mt-2 Edit Reflection
  = simple_form_for @reflection, url: reflection_path(@reflection), method: :patch do |f|
    .row.form-group
      .col-md-12
        = f.input_field :title, placeholder: 'Reflection Title', class: 'form-control', id: 'reflectionTitle'
    .row.form-group
      .col-md-12
        = f.text_area :story, placeholder: 'Write your story here', class: 'form-control summernote', id: 'reflectionStory', rows: 20
    .row.form-group
      .col-md-12
        = link_to 'back', user_path(current_user), class: 'btn btn-secondary'
        = f.button :submit, 'Save Reflection', class: 'btn btn-primary ml-1'

app/views/reflections/index.html.slim
.container
  - if @reflections.empty?
    .jumbotron.text-center.mt-3
      = icon('clone', class: 'fa-4x')
      h3 We cannot find any reflections that are currently visisble to you.
      p.lead Click the button to find out more about creating your reflections.
      a.btn.btn-primary href='#' Find out more
  - else
    .card-columns.mt-3
      - @reflections.each do |reflection|
        = render partial: "layouts/reflections/reflection_card", locals: {reflection: reflection, review: !@review_reflection_ids.nil? && @review_reflection_ids.include?(reflection.id) ? reflection.reflection_reviews.first :  nil }

app/views/reflections/privacy.html.slim
.container
  .card.mt-3
    .card-body
      .lead
        | Privacy Settings for&nbsp;
        span.text-primary = @reflection.title
      p
        | This is currently a&nbsp;
        span.text-muted = @reflection.privacy
        | &nbsp;post.&nbsp;
        - if @reflection.privacy == 'Private'
          span Search for users to share reflections with.
        - else
          span Everyone can see this reflection as of now. Change privacy settings to share with specific users only.
      *privacy_share_form(@reflection.privacy)
        input#share_input.form-control.tokenize type='text' data-personals="#{@personals_json}"

      - if @reflection.privacy == 'Private'
        button#share_btn.btn.btn-primary.pull-right.btn-sm.ml-2 #{icon('share')} Share
      .btn-group.pull-right
        button#dropdownButton.btn.btn-sm.btn-primary.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" = @reflection.privacy=="Private" ? icon('lock')+" Private" : icon('globe')+" Public"
        .dropdown-menu aria-labelledby="dropdownButton"
          a.dropdown-item href=update_reflection_privacy_path(@reflection, privacy: 'Private') data-method="post"
            - if @reflection.privacy == "Private"
              span.text-primary #{icon('lock')} Private
            - else
              span #{icon('lock')} Private
          a.dropdown-item href=update_reflection_privacy_path(@reflection, privacy: 'Public') data-method="post"
            - if @reflection.privacy == "Public"
              span.text-primary #{icon('globe')} Public
            - else
              span #{icon('globe')} Public
      a.btn.btn-light.pull-right.btn-sm.mr-2 href=reflection_path(@reflection) View Reflection

form#privacy_form.hidden method="post" action=authorise_personals_path(@reflection)
  input#privacy_input type="hidden" name="authorised_personals" value=""
  input type="hidden" name=request_forgery_protection_token.to_s value=form_authenticity_token

app/views/reflections/review.html.slim
.container
  .card.mt-3
    .card-body
      .lead
        | Review Settings for&nbsp;
        span.text-primary = @reflection.title
      p Add users as reviewers and submit to them for critique.
      .form-group
        input#review_input.form-control.tokenize type='text' data-reviewers="#{@reviewers_json}"
      button#review_btn.btn.btn-primary.pull-right.btn-sm Submit for review
      a.btn.btn-light.pull-right.btn-sm.mr-2 href=reflection_path(@reflection) View Reflection

form#review_form.hidden method="post" action=submit_for_review_path(@reflection)
  input#reviewers_input type="hidden" name="reviewers" value=""
  input type="hidden" name=request_forgery_protection_token.to_s value=form_authenticity_token

app/views/reflections/settings.html.slim
.container
  #privacy_section.card.mt-3
    .card-body
      .lead
        | Privacy Settings for&nbsp;
        span.text-primary = @reflection.title
      p
        | This is currently a&nbsp;
        span.text-muted = @reflection.privacy
        | &nbsp;post.&nbsp;
        - if @reflection.privacy == 'Private'
          span Search for users to share reflections with.
        - else
          span Everyone can see this reflection as of now. Change privacy settings to share with specific users only.
      *privacy_share_form(@reflection.privacy)
        input#share_input.form-control.tokenize type='text' data-personals="#{@personals_json}"

      - if @reflection.privacy == 'Private'
        button#share_btn.btn.btn-primary.pull-right.btn-sm.ml-2 #{icon('share')} Share
      .btn-group.pull-right
        button#dropdownButton.btn.btn-sm.btn-primary.dropdown-toggle type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" = @reflection.privacy=="Private" ? icon('lock')+" Private" : icon('globe')+" Public"
        .dropdown-menu aria-labelledby="dropdownButton"
          a.dropdown-item href=update_reflection_privacy_path(@reflection, privacy: 'Private') data-method="post"
            - if @reflection.privacy == "Private"
              span.text-primary #{icon('lock')} Private
            - else
              span #{icon('lock')} Private
          a.dropdown-item href=update_reflection_privacy_path(@reflection, privacy: 'Public') data-method="post"
            - if @reflection.privacy == "Public"
              span.text-primary #{icon('globe')} Public
            - else
              span #{icon('globe')} Public

  #review_section.card.mt-3
    .card-body
      .lead
        | Review Settings for&nbsp;
        span.text-primary = @reflection.title
      p Add users as reviewers and submit to them for critique.
      .form-group
        input#review_input.form-control.tokenize type='text' data-reviewers="#{@reviewers_json}"
      button#review_btn.btn.btn-primary.pull-right.btn-sm #{icon('paper-plane')} Submit for review

  .card.mt-3
    .card-body.text-center
      .lead.mb-2 I am done with my reflection settings.
      a.btn.btn-lg.btn-primary href=reflection_path(@reflection) Bring me back to see my reflection!

form#privacy_form.hidden method="post" action=authorise_personals_path(@reflection)
  input#privacy_input type="hidden" name="authorised_personals" value=""
  input type="hidden" name=request_forgery_protection_token.to_s value=form_authenticity_token

form#review_form.hidden method="post" action=submit_for_review_path(@reflection)
  input#reviewers_input type="hidden" name="reviewers" value=""
  input type="hidden" name=request_forgery_protection_token.to_s value=form_authenticity_token

app/views/reflections/show.html.slim
.container.mb-3
  .card.mt-3
    .card-body
      h4.lead.text-primary = @reflection.title
      p.card-text = @reflection.story.html_safe
      p.card-text
      - if @reflection.privacy == "Private"
        span.badge.badge-success
          strong #{icon('lock')} #{@reflection.privacy}&nbsp;
          | reflection&nbsp;
        - if @reflection.authorised_personals.empty?
          | which is currently not shared with anyone.
        - else
          br
          span Shared with&nbsp;
          - @reflection.authorised_personals.each do |personal|
            span.badge.badge-primary #{personal.name}
            | &nbsp;
      - else
        | This is a&nbsp;
        strong #{icon('globe')} #{@reflection.privacy}&nbsp;
        | reflection which is publicly available for anyone to read.
      p.card-text
        small.text-muted Created on #{@reflection.created_at.strftime("%-d %B %Y")} by #{@reflection.user.name}

      .btn-group
        a.btn.btn-sm.btn-secondary href=reflections_path Back
        - if user_signed_in? && current_user == @reflection.user
          a.btn.btn-sm.btn-light href=edit_reflection_path(@reflection)
            span Edit
          a.btn.btn-sm.btn-light href=reflection_privacy_path(@reflection) Privacy
          a.btn.btn-sm.btn-light href=reflection_review_path(@reflection) Submissions

  - if !@reflection_reviews.empty?
    #reviews_section
      - @reflection_reviews.each do |review|
        .card.mt-3
          .card-body
            span.badge.badge-primary Complete Review
            p.card-text = review.content.html_safe
            p.card-text
              small.text-muted Created on #{review.created_at.strftime("%-d %B %Y")} by #{review.reviewer.name}


  #comments_section.card.mt-3
    .card-body
      = commontator_thread(@reflection)