config/routes.rb
Rails.application.routes.draw do
  mount Commontator::Engine => '/commontator'

  devise_for :users

  resources :users, only: [:index, :show, :update]
  resources :reflections, only: [:index, :show, :edit, :update]
  resources :reviews, only: [:index, :show, :edit, :update]

  root 'home#index'
  get 'demo', to: 'home#demo'
  get 'about', to: 'home#about'
  get 'users/typeahead/:query', to: 'users#typeahead'
  get 'add_reflection', to: 'reflections#add', as: 'add_reflection'
  get 'reflections/:id/privacy', to: 'reflections#privacy', as: 'reflection_privacy'
  get 'reflections/:id/review', to: 'reflections#review', as: 'reflection_review'
  get 'reflections/:id/settings', to: 'reflections#settings', as: 'reflection_settings'

  post 'reflections/new', to: 'reflections#new', as: 'new_reflection'
  post 'reflections/:id/authorise', to: 'reflections#authorise', as: 'authorise_personals'
  post 'reflections/:id/update_privacy', to: 'reflections#update_privacy', as: 'update_reflection_privacy'
  post 'reflections/:id/', to: 'reflections#submit_for_review', as: 'submit_for_review'
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable and :omniauthable

  acts_as_commontator

  validates :name, :presence => true, :uniqueness => true

  has_many :reflections

  has_many :reflection_privacies, class_name: "Privacy", foreign_key: "authorised_personal_id"
  has_many :visible_reflections, through: :reflection_privacies, source: :reflection

  has_many :reflection_reviews, class_name: "Review", foreign_key: "reviewer_id"
  has_many :request_reflections, through: :reflection_reviews, source: :reflection
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def index
  end

  def show
    @user = User.find(user_id_params)
    if user_signed_in?
      @reflections = @user.reflections.order('updated_at DESC')
      @request_reflections = current_user.request_reflections.order('updated_at DESC')
      reflections_ids = @reflections.map{|reflection| reflection.id}
      @review_requests = Review.where(reflection_id: reflections_ids)
    else
      @reflections = @user.reflections.order('updated_at DESC').where(privacy: 1)
    end
  end

  def update
    user = User.find(user_id_params)
    user.name = user_name_params[:name]
    user.save
    flash[:notice] = 'User name successfully updated!'
    redirect_to edit_user_registration_path
  end

  def typeahead
    query = params[:query]
    search  = User.where('name LIKE :query OR email LIKE :query', query: "%#{query}%")
    results = search.map { |q| {'value': "#{q.name}; #{q.email}", 'id': "#{q.id}"} }.to_json

    render json: results
  end

  private

  def user_id_params
    params.require(:id)
  end

  def user_name_params
    params.require(:user).permit(
      :name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/show.html.slim
.container.mb-2
  - if user_signed_in?
    .lead.text-center.mt-2 #{current_user.name}'s Dashboard
    hr
    .row
      .col-md-6
        - if @reflections.empty?
          .jumbotron.text-center
            = icon('clone', class: 'fa-4x')
            h3 We cannot find any reflections that belong to you.
            p.lead Click the button below to start creating a reflection.
            a.btn.btn-primary href=add_reflection_path Create a reflection
        - else
          .row
            .col-md-12
              a.btn.btn-light.col-xs-12.col-sm-12.col-md-12.mb-3 href=add_reflection_path #{icon('plus')} Create new reflection
          - @reflections.each do |reflection|
            .mb-3
              = render partial: "layouts/reflections/reflection_card", locals: { reflection: reflection, review: nil }

      .col-md-6
        p.text-center
          strong Pending Reviews
        - if !@request_reflections.empty?
          .alert.alert-warning role="alert"
            span You have #{@request_reflections.count} reflections awaiting review! Click&nbsp;
            a.btn.btn-warning.btn-sm href=reviews_path Review
            span &nbsp;to begin!

        - if !@review_requests.empty?
          - @review_requests.each do |review_request|
            - reflection = @reflections.find {|r| r.id == review_request.reflection_id }
            .mb-3
              .card.border-warning
                .card-body
                  - if review_request.status == "Incomplete"
                    span.badge.badge-warning Incomplete Review
                    .lead.my-2
                      span You have requested&nbsp;
                      strong = review_request.reviewer.name
                      span &nbsp;to review:&nbsp;
                      span.text-primary = reflection.title
                    a.btn.btn-warning.btn-sm href=reflection_review_path(reflection) View Review Settings
                  - else
                    span.badge.badge-primary Complete Review
                    .lead.my-2
                      strong = review_request.reviewer.name
                      span &nbsp;has completed the review for:&nbsp;
                      span.text-primary = reflection.title
                    p.card-text = strip_tags(review_request.content).truncate_words(100)
                    a.btn.btn-sm.btn-primary href="#{reflection_path(reflection)}#reviews_section" View Review
        - else
          .jumbotron.text-center
            = icon('paper-plane', class: 'fa-4x')
            h3 No reflection review submissions found.
            p.lead Submit reflections to peers and mentors for review to populate this section.
  - else
    .lead.text-center.mt-2 #{@user.name}'s Reflections
    hr
    - if @reflections.empty?
      .jumbotron.text-center.mt-3
        = icon('clone', class: 'fa-4x')
        h3 We cannot find any reflections from this user that are currently visisble to you.
        p.lead Do you know this user personally? You might want to ask him to change his reflection's privacy setting to public.
    - else
      .card-columns.mt-3
        - @reflections.each do |reflection|
          = render partial: "layouts/reflections/reflection_card", locals: {reflection: reflection, review: !@review_reflection_ids.nil? && @review_reflection_ids.include?(reflection.id) ? reflection.reflection_reviews.first :  nil }