config/routes.rb
Rails.application.routes.draw do
  mount Commontator::Engine => '/commontator'

  devise_for :users

  resources :users, only: [:index, :show, :update]
  resources :reflections, only: [:index, :show, :edit, :update]
  resources :reviews, only: [:index, :show, :edit, :update]

  root 'home#index'
  get 'demo', to: 'home#demo'
  get 'about', to: 'home#about'
  get 'users/typeahead/:query', to: 'users#typeahead'
  get 'add_reflection', to: 'reflections#add', as: 'add_reflection'
  get 'reflections/:id/privacy', to: 'reflections#privacy', as: 'reflection_privacy'
  get 'reflections/:id/review', to: 'reflections#review', as: 'reflection_review'
  get 'reflections/:id/settings', to: 'reflections#settings', as: 'reflection_settings'

  post 'reflections/new', to: 'reflections#new', as: 'new_reflection'
  post 'reflections/:id/authorise', to: 'reflections#authorise', as: 'authorise_personals'
  post 'reflections/:id/update_privacy', to: 'reflections#update_privacy', as: 'update_reflection_privacy'
  post 'reflections/:id/', to: 'reflections#submit_for_review', as: 'submit_for_review'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  include ReviewsHelper

  def index
    @complete_reviews = Review.includes(:reflection).where(reviewer: current_user, status: 'Complete')
    @incomplete_reviews = Review.includes(:reflection).where(reviewer: current_user, status: 'Incomplete')
  end

  def show
    @review = Review.find(review_id_params)
    if @review.content.blank?
      @review.content = review_html('default')
    end
  end

  def edit
    @review = Review.find(review_id_params)
  end

  def update
    review = Review.find(review_id_params)
    review.content = review_content_params['content']
    review.status = review_content_params['status']
    review.save

    redirect_to :back
  end

  private

  def review_id_params
    params.require(:id)
  end

  def review_content_params
    params.require(:review).permit(
      :content, :status)
  end
end

app/views/reviews/edit.html.slim
h1 Reviews#edit
p Find me in app/views/reviews/edit.html.slim

app/views/reviews/index.html.slim
.container.my-2
  .lead.text-center Reflection Reviews dashboard
  hr
  .row
    .col-md-6
      p.text-center
        strong Completed Reviews
      - if @complete_reviews.empty?
        .jumbotron.text-center
          = icon('check-square-o', class: 'fa-4x')
          h3 You do not have any completed reviews at the moment.
          p.lead Submitted reviews will be seen in this column.
      - else
        - @complete_reviews.each do |review|
          .mb-3
            = render partial: "layouts/reflections/reflection_card", locals: {reflection: review.reflection, review: review}
    .col-md-6
      p.text-center
        strong Incomplete Reviews
      - if @incomplete_reviews.empty?
        .jumbotron.text-center
          = icon('square-o', class: 'fa-4x')
          h3 You do not have any new incomplete reviews at the moment.
          p.lead Ask your peers and mentees to send reflections to you for review.
      - else
        - @incomplete_reviews.each do |review|
          .mb-3
            = render partial: "layouts/reflections/reflection_card", locals: {reflection: review.reflection, review: review}

app/views/reviews/show.html.slim
.container.mb-3
  .card.card-info.mt-3
    .card-body
      h4.lead
        span.text-success You are reviewing&nbsp;
        span.text-primary #{@review.reflection.title}&nbsp;
        span written by&nbsp;
        span.text-primary #{@review.reflection.user.name}
      p.card-text = @review.reflection.story.html_safe
      p.card-text
        small.text-muted Created on #{@review.reflection.created_at.strftime("%-d %B %Y")} by #{@review.reflection.user.name}
  .card.card-success.mt-3
    .card-body
      h4.lead Write review here.
      = simple_form_for @review, url: review_path(@review), method: :patch, html: {id: :review_form} do |f|
        .row.form-group
          .col-md-12
            = f.text_area :content, placeholder: 'Write review here!', class: 'form-control summernote', id: 'reflectionReview', rows: 20
            = f.hidden_field :status, id: 'review_status'
        .row.form-group
          .col-md-12
            button#review_button.btn.btn-warning.mr-1
              - if @review.status == "Incomplete"
                span Publish Review
              - else
                span Unpublish Review
            = f.button :submit, 'Save Review', class: 'btn btn-light mr-1'
            = link_to 'back', user_path(current_user), class: 'btn btn-light'

app/views/reviews/update.html.slim
h1 Reviews#update
p Find me in app/views/reviews/update.html.slim